version: "3.8"

services:
  db:
    image: postgres:16
    container_name: rails8new_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails8new_development
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
